<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>ChipLauncher.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="ChipLauncher.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.4" />
        <PackageReference Include="SharpCompress" Version="0.49.1" />
        <PackageReference Include="SukiUI" Version="7.0.1" />
        <PackageReference Include="System.Reflection.MetadataLoadContext" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="obj\" />
    </ItemGroup>

    <Target Name="KillChipLauncher" BeforeTargets="CoreCompile">
        <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File KillChipLauncher.ps1" IgnoreExitCode="true" />
    </Target>

</Project>
